name: Post to Threads

on:
  schedule:
    - cron: '0 * * * *'  # Run every hour
  workflow_dispatch:  # Allow manual triggers

jobs:
  post_to_threads:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run post to Threads script
      env:
        THREADS_ACCESS_TOKEN: ${{ secrets.THREADS_ACCESS_TOKEN }}
        THREADS_USER_ID: ${{ secrets.THREADS_USER_ID }}
      run: python src/post_to_threads.py
    - name: Commit changes to queue
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add queue.json
        git commit -m "Update queue after posting" -a || echo "No changes to commit"
        git push
