name: Update Queue

on:
  push:
    paths:
      - 'queue.json'

jobs:
  update_queue:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Sort and clean queue
      run: |
        python src/queue_manager.py
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add queue.json
        git commit -m "Update and sort queue" -a || echo "No changes to commit"
        git push
